apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
spec:
  selector:
    matchLabels:
      app: my-app
      team: team-1
  replicas: 3
  template:
    metadata:
      name: empapp
      labels:
        app: my-app
        team: team-1
    spec:
      containers:
        - name: empapp
          image: rgupta00/empapp:1.1
          resources:
           limits:
            memory: "128Mi"
            cpu: "500m"
          ports:
           - containerPort: 8080


  