eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: 8070
spring:
  config:
    import: optional:configserver:http://localhost:8071/
  application:
    name: eurekaserver
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
  info:
    env:
      enabled: true
info:
  message: "welcome to eureka application default profile"
  name: "raj default profile eureka"

