apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  username: cmFqCg==
  password: cmFqMTIzCg==
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: "app_username"
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: username
    - name: "app_password"
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: password
    args:
    - env            