apiVersion: v1
kind: Pod
metadata:
  name: empapp-v1
  labels:
    app: empapp-pod
    type: prod
    ver: "1.1"
spec:
  containers:
  - name: empapp-pod
    image: rgupta00/empapp:1.1
    ports:
      - containerPort: 8080