# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: eurekaserver-deployment
serviceName: eurekaserver
appLabel: eurekaserver
appName: eurekaserver

replicaCount: 1

image:
  repository: rgupta00/eurekaserver
  tag: v3

containerPort: 8070

service:
  type: LoadBalancer
  port: 8070
  targetPort: 8070

appname_enabled: true
profile_enabled: false
config_enabled: true
eureka_enabled: false