server:
  port: 8090
  servlet:
    context-path: /productapp
spring:
  jmx:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootdemo
management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      livenessstate:
        enabled: true
      readinessstate:
        enabled: true
      show-details: always
      probes:
        enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      base-path: /busycoder
      exposure:
        include: "*"
logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
info:
  app:
    name: "myapp"
    dev: "raj"