apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
    - name: mypod
      image: nginx:1.1
      resources:
       limits:
         memory: "128Mi"
         cpu: "500m"
      ports:
        - containerPort: 80
