server:
  port: 8090
  servlet:
    context-path: /productapp
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootdemo
logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG