# vinsdocker/k8s-probe-demo uses nginx
# nginx will start after 10 seconds
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: probe-demo
    image: rgupta00/k8s-probe-demo
    resources:
       limits:
         memory: "128Mi"
         cpu: "500m"
    startupProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 1
      failureThreshold: 30
    livenessProbe:
      httpGet:
        path: /live.html
        port: 80
      periodSeconds: 1
      failureThreshold: 3      