server:
  port: 8071
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: file:///C:/configfiles
          force-pull: true
          clone-on-start: true
          default-label: master
          timeout: 5
