apiVersion: apps/v1
kind: Deployment
metadata:
  name: empapp-deploy
  annotations:
    kubernetes.io/change-cause: "deploying v1"
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "100%"
  selector:
    matchLabels:
      app:  empapp-service
  replicas: 3
  template:
    metadata:
      labels:
        app:  empapp-service
    spec:
      containers:
      - name:  empapp-service
        image: rgupta00/empapp:1.1
        ports:
        - name: "app-port"
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: empapp-svc
spec:
  type: NodePort
  selector:
    app: empapp-service
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
